FROM python:3.12-slim

RUN apt-get update && apt-get install -y wget gnupg2 cron locales unzip curl openssl

WORKDIR /app

COPY requirements.txt .

RUN pip install fastapi-cli
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["fastapi", "run", "app.py"]